name: Inception
# ==============================================================================
services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
    restart: always
    volumes:
      - data-drive:/home/data-drive:rw
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - DB_COLLATE=${DB_COLLATE:-utf8mb4_uca1400_ai_ci}
      - MARIADB_PORT=${MARIADB_PORT:-3306}
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - MARIADB_USER_PASSWORD_FILE=/run/secrets/mariadb_user_password
    secrets:
      - mariadb_root_password
      - mariadb_user_password
    networks:
      - data-net
# -----
  wordpress:
    build:
      context: ./requirements/wordpress/.
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    restart: always
    volumes:
      - web-drive:/home/web-drive:rw
    environment:
      - WORDPRESS_VERSION=${WORDPRESS_VERSION:-7.0.4}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
      - WORDPRESS_DB_TABLE_PREFIX=${WORDPRESS_DB_TABLE_PREFIX:-wordpress_}
      - DB_CHARSET=${DB_CHARSET:-utf8mb4}
      - DB_COLLATE=${DB_COLLATE:-utf8mb4_uca1400_ai_ci}
      - WORDPRESS_DOMAIN=${WORDPRESS_DOMAIN:?}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE:-Inception}
      - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME:-owner}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-admin@invalid.email}
      - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME:-author}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL:-author@invalid.email}
      - NGINX_PORT=${NGINX_PORT:-443}
      - WORDPRESS_FPM_PORT=${WORDPRESS_FPM_PORT:-9000}
      - MARIADB_PORT=${MARIADB_PORT:-3306}
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wordpress_admin_password
      - WORDPRESS_USER_PASSWORD_FILE=/run/secrets/wordpress_user_password
      - MARIADB_USER_PASSWORD_FILE=/run/secrets/mariadb_user_password
    secrets:
      - mariadb_user_password
      - wordpress_admin_password
      - wordpress_user_password
    networks:
      - data-net
      - web-net
# -----
  nginx:
    build:
      context: requirements/nginx/.
    depends_on:
      wordpress:
        condition: service_healthy
        restart: true
    restart: always
    volumes:
      - web-drive:/home/web-drive:ro
    environment:
      - WORDPRESS_DOMAIN=${WORDPRESS_DOMAIN:?}
      - ADMINER_SUBDOMAIN=${ADMINER_SUBDOMAIN:-adminer}
      - ADMINER_PORT=${ADMINER_PORT:-8080}
      - STATIC_SUBDOMAIN=${STATIC_SUBDOMAIN:-static}
      - STATIC_PORT=${STATIC_PORT:-8081}
      - NGINX_PORT=${NGINX_PORT:-443}
      - WORDPRESS_FPM_PORT=${WORDPRESS_FPM_PORT:-9000}
    networks:
      - web-net
    ports:
      - ${NGINX_PORT:-443}:${NGINX_PORT:-443}
# -----
  adminer:
    build:
      context: requirements/bonus/adminer/.
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    restart: always
    environment:
      - ADMINER_PORT=${ADMINER_PORT:-8080}
    networks:
      - data-net
      - web-net
# -----
  static_website:
    build:
      context: requirements/bonus/static_website/.
    restart: always
    environment:
      - STATIC_PORT=${STATIC_PORT:-8081}
    networks:
      - web-net
# ==============================================================================
volumes:
  data-drive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_ROOT_PATH:-/home/vpoka/data}/${DATA_DRIVE_DIR:-database}
# -----
  web-drive:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_ROOT_PATH:-/home/vpoka/data}/${WEB_DRIVE_DIR:-website}
# ==============================================================================
secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt
# -----
  mariadb_user_password:
    file: ./secrets/mariadb_user_password.txt
# -----
  wordpress_admin_password:
    file: ./secrets/wordpress_admin_password.txt
# -----
  wordpress_user_password:
    file: ./secrets/wordpress_user_password.txt
# ==============================================================================
networks:
  data-net:
    driver: bridge
# -----
  web-net:
    driver: bridge
