name: Inception
# ==============================================================================
services:
  # nginx:
  #   build: requirements/nginx/.
  #   ports:
  #     - 80:80
  #   environment:
  #     - DOMAIN_NAME=${DOMAIN_NAME:-localhost}
# ------------------------------------------------------------------------------
  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - database:/home/data:rw
    environment:
      - DB_NAME=${MARIADB_WORDPRESS_DATABASE_NAME:?}
      - DB_USER=${MARIADB_WORDPRESS_USER_NAME:?}
      - DATABASE_CHARSET=${DATABASE_CHARSET:?}
      - DATABASE_COLLATE=${DATABASE_COLLATE:?}
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - MARIADB_WORDPRESS_USER_PASSWORD_FILE=/run/secrets/mariadb_wordpress_user_password
    secrets:
      - mariadb_root_password
      - mariadb_wordpress_user_password
# ------------------------------------------------------------------------------
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy
        # restart: true
    restart: always
    volumes:
      - website:/home/data:rw
    environment:
      - DATABASE_NAME=${MARIADB_WORDPRESS_DATABASE_NAME:?}
      - DATABASE_USER=${MARIADB_WORDPRESS_USER_NAME:?}
      - DATABASE_TABLE_PREFIX=${MARIADB_WORDPRESS_DATABASE_TABLE_PREFIX:?}
      - DATABASE_CHARSET=${DATABASE_CHARSET:?}
      - DATABASE_COLLATE=${DATABASE_COLLATE:?}
      - DOMAIN=${WORDPRESS_DOMAIN:?}
      - TITLE=${WORDPRESS_WEBSITE_TITLE:?}
      - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME:?}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_USER_NAME=${WORDPRESS_USER_NAME:?}
      - WORDPRESS_USER_EMAIL=${WORDPRESS_USER_EMAIL:?}
      - MARIADB_WORDPRESS_USER_PASSWORD_FILE=/run/secrets/mariadb_wordpress_user_password
      - WORDPRESS_ADMIN_PASSWORD_FILE=/run/secrets/wordpress_admin_password
      - WORDPRESS_USER_PASSWORD_FILE=/run/secrets/wordpress_user_password
    secrets:
      - mariadb_wordpress_user_password
      - wordpress_admin_password
      - wordpress_user_password
# ==============================================================================
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DIR:?}
# ------------------------------------------------------------------------------
  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEB_DIR:?}
# ==============================================================================
# TODO: define an internal docker network
networks:
  default:
    # internal: true # if uncommented, installation of wordpress files from internet fails, as this setting does not allow ANY connection to the outside
# ==============================================================================
secrets:
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt
  mariadb_wordpress_user_password:
    file: ./secrets/mariadb_wordpress_user_password.txt
  wordpress_admin_password:
    file: ./secrets/wordpress_admin_password.txt
  wordpress_user_password:
    file: ./secrets/wordpress_user_password.txt
