name: Inception

services:
  # nginx:
  #   build: requirements/nginx/.
  #   ports:
  #     - 80:80
  #   environment:
  #     - DOMAIN_NAME=${DOMAIN_NAME:-localhost}

  mariadb:
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - database:/home/data:rw
    environment:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  # wordpress:
  #   build: ./requirements/wordpress
  #   depends_on:
  #     mariadb:
  #       condition: service_healthy
  #       restart: true
  #   restart: always
  #   volumes:
  #     - website:/home/data:rw
  #   environment:
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_DIR:?}

  website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WEB_DIR:?}

# TODO:
# networks:

# TODO: probably not needed though.
# secrets:
